import { Injectable, Optional, SkipSelf } from '@angular/core';
import { GameDataComponent } from '../components/game-data/game-data.component';
import { Character, Element, Species } from '../models/game-data.model';

@Injectable({
  providedIn: 'root',
})
export class GameDataService {
  public characterData: Character[] = [
    {
      id: 0,
      firstName: 'Dart',
      lastName: 'Feld',
      element: Element.FIRE,
      species: Species.HUMAN,
      additions: [
        {
          id: 0,
          name: 'Double Slash',
          unlockLevel: 1,
          unlockOrder: 1,
          damage: 150,
          sp: 35,
          levels: [
            {
              level: 1,
              multiplier: {
                sp: 0,
                damage: 0,
              },
            },
            {
              level: 2,
              multiplier: {
                sp: 0,
                damage: 5,
              },
            },
            {
              level: 3,
              multiplier: {
                sp: 0,
                damage: 10,
              },
            },
            {
              level: 4,
              multiplier: {
                sp: 0,
                damage: 20,
              },
            },
            {
              level: 5,
              multiplier: {
                sp: 0,
                damage: 35,
              },
            },
          ],
          hitData: [
            {
              flag: 192,
              blueSquareFrames: 15,
              postHitPauseFrames: 9,
              actionInputFrames: 3,
              damage: 100,
              sp: 30,
              lastHit: false,
              panningDistance: 0,
              cameraDistanceOne: 0,
              cameraDistanceTwo: 8,
              moveToMonsterFrames: 5,
              distance: 12,
              pauseFrames: 0,
            },
            {
              flag: 192,
              blueSquareFrames: 19,
              postHitPauseFrames: 11,
              actionInputFrames: 1,
              damage: 50,
              sp: 5,
              lastHit: true,
              panningDistance: 0,
              cameraDistanceOne: 8,
              cameraDistanceTwo: 3,
              moveToMonsterFrames: 3,
              distance: 10,
              pauseFrames: 0,
            },
          ],
        },
      ],
      bodyStats: [
        { level: 0, attack: 0, defense: 0, speed: 50, magicAttack: 0, magicDefense: 0, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 0 },
        { level: 1, attack: 2, defense: 4, speed: 50, magicAttack: 3, magicDefense: 4, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 30 },
        { level: 2, attack: 4, defense: 5, speed: 50, magicAttack: 5, magicDefense: 5, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 60 },
        { level: 3, attack: 6, defense: 7, speed: 50, magicAttack: 7, magicDefense: 7, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 90 },
        { level: 4, attack: 8, defense: 10, speed: 50, magicAttack: 9, magicDefense: 9, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 120 },
        { level: 5, attack: 11, defense: 12, speed: 50, magicAttack: 11, magicDefense: 11, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 150 },
        { level: 6, attack: 13, defense: 14, speed: 50, magicAttack: 13, magicDefense: 13, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 180 },
        { level: 7, attack: 15, defense: 16, speed: 50, magicAttack: 15, magicDefense: 15, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 210 },
        { level: 8, attack: 18, defense: 19, speed: 50, magicAttack: 17, magicDefense: 17, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 240 },
        { level: 9, attack: 20, defense: 21, speed: 50, magicAttack: 19, magicDefense: 19, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 270 },
        { level: 10, attack: 22, defense: 23, speed: 50, magicAttack: 21, magicDefense: 21, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 300 },
        { level: 11, attack: 25, defense: 26, speed: 50, magicAttack: 24, magicDefense: 24, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 330 },
        { level: 12, attack: 27, defense: 28, speed: 50, magicAttack: 26, magicDefense: 26, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 413 },
        { level: 13, attack: 30, defense: 31, speed: 50, magicAttack: 29, magicDefense: 29, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 496 },
        { level: 14, attack: 32, defense: 33, speed: 50, magicAttack: 31, magicDefense: 32, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 579 },
        { level: 15, attack: 35, defense: 36, speed: 50, magicAttack: 34, magicDefense: 34, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 662 },
        { level: 16, attack: 37, defense: 38, speed: 50, magicAttack: 36, magicDefense: 37, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 745 },
        { level: 17, attack: 40, defense: 41, speed: 50, magicAttack: 39, magicDefense: 40, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 828 },
        { level: 18, attack: 42, defense: 43, speed: 50, magicAttack: 41, magicDefense: 42, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 911 },
        { level: 19, attack: 45, defense: 46, speed: 50, magicAttack: 44, magicDefense: 45, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 994 },
        { level: 20, attack: 47, defense: 48, speed: 50, magicAttack: 46, magicDefense: 48, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1077 },
        { level: 21, attack: 50, defense: 51, speed: 50, magicAttack: 49, magicDefense: 51, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1160 },
        { level: 22, attack: 52, defense: 53, speed: 50, magicAttack: 51, magicDefense: 53, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1272 },
        { level: 23, attack: 55, defense: 56, speed: 50, magicAttack: 54, magicDefense: 55, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1384 },
        { level: 24, attack: 57, defense: 58, speed: 50, magicAttack: 56, magicDefense: 57, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1496 },
        { level: 25, attack: 60, defense: 61, speed: 50, magicAttack: 59, magicDefense: 60, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1608 },
        { level: 26, attack: 62, defense: 63, speed: 50, magicAttack: 61, magicDefense: 62, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1720 },
        { level: 27, attack: 65, defense: 66, speed: 50, magicAttack: 64, magicDefense: 64, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1832 },
        { level: 28, attack: 67, defense: 68, speed: 50, magicAttack: 66, magicDefense: 67, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 1944 },
        { level: 29, attack: 70, defense: 71, speed: 50, magicAttack: 69, magicDefense: 69, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2056 },
        { level: 30, attack: 72, defense: 73, speed: 50, magicAttack: 71, magicDefense: 71, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2168 },
        { level: 31, attack: 75, defense: 76, speed: 50, magicAttack: 74, magicDefense: 74, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2280 },
        { level: 32, attack: 77, defense: 78, speed: 50, magicAttack: 76, magicDefense: 76, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2399 },
        { level: 33, attack: 80, defense: 81, speed: 50, magicAttack: 79, magicDefense: 79, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2518 },
        { level: 34, attack: 82, defense: 83, speed: 50, magicAttack: 81, magicDefense: 82, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2637 },
        { level: 35, attack: 85, defense: 86, speed: 50, magicAttack: 84, magicDefense: 84, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2756 },
        { level: 36, attack: 87, defense: 88, speed: 50, magicAttack: 86, magicDefense: 87, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2875 },
        { level: 37, attack: 90, defense: 91, speed: 50, magicAttack: 89, magicDefense: 90, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 2994 },
        { level: 38, attack: 92, defense: 93, speed: 50, magicAttack: 91, magicDefense: 92, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 3113 },
        { level: 39, attack: 95, defense: 96, speed: 50, magicAttack: 94, magicDefense: 95, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 3232 },
        { level: 40, attack: 97, defense: 98, speed: 50, magicAttack: 96, magicDefense: 98, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 3351 },
        { level: 41, attack: 100, defense: 101, speed: 50, magicAttack: 99, magicDefense: 101, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 3470 },
        { level: 42, attack: 102, defense: 103, speed: 50, magicAttack: 101, magicDefense: 103, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 3729 },
        { level: 43, attack: 105, defense: 105, speed: 50, magicAttack: 104, magicDefense: 105, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 3988 },
        { level: 44, attack: 107, defense: 108, speed: 50, magicAttack: 106, magicDefense: 107, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 4247 },
        { level: 45, attack: 110, defense: 110, speed: 50, magicAttack: 109, magicDefense: 110, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 4506 },
        { level: 46, attack: 112, defense: 113, speed: 50, magicAttack: 111, magicDefense: 112, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 4765 },
        { level: 47, attack: 115, defense: 115, speed: 50, magicAttack: 114, magicDefense: 114, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 5024 },
        { level: 48, attack: 117, defense: 118, speed: 50, magicAttack: 116, magicDefense: 117, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 5283 },
        { level: 49, attack: 120, defense: 120, speed: 50, magicAttack: 119, magicDefense: 119, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 5542 },
        { level: 50, attack: 122, defense: 123, speed: 50, magicAttack: 121, magicDefense: 121, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 5801 },
        { level: 51, attack: 125, defense: 125, speed: 50, magicAttack: 124, magicDefense: 124, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 6060 },
        { level: 52, attack: 127, defense: 128, speed: 50, magicAttack: 126, magicDefense: 126, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 6220 },
        { level: 53, attack: 130, defense: 131, speed: 50, magicAttack: 129, magicDefense: 129, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 6380 },
        { level: 54, attack: 133, defense: 133, speed: 50, magicAttack: 132, magicDefense: 132, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 6540 },
        { level: 55, attack: 136, defense: 136, speed: 50, magicAttack: 135, magicDefense: 135, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 6700 },
        { level: 56, attack: 138, defense: 139, speed: 50, magicAttack: 138, magicDefense: 138, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 6860 },
        { level: 57, attack: 141, defense: 141, speed: 50, magicAttack: 141, magicDefense: 141, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 7020 },
        { level: 58, attack: 144, defense: 144, speed: 50, magicAttack: 144, magicDefense: 144, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 7180 },
        { level: 59, attack: 147, defense: 147, speed: 50, magicAttack: 147, magicDefense: 147, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 7340 },
        { level: 60, attack: 150, defense: 150, speed: 50, magicAttack: 150, magicDefense: 150, attackHit: 0, attackAvoid: 0, magicHit: 0, magicAvoid: 0, hp: 7500 },
      ],
      dragoons: [
        {
          element: Element.FIRE,
          spells: null,
          dragoonStats: [
            {
              attack: 150,
              defense: 150,
              magicAttack: 200,
              magicDefense: 200,
            },
            {
              attack: 155,
              defense: 155,
              magicAttack: 210,
              magicDefense: 210,
            },
            {
              attack: 160,
              defense: 160,
              magicAttack: 220,
              magicDefense: 220,
            },
            {
              attack: 165,
              defense: 165,
              magicAttack: 230,
              magicDefense: 230,
            },
            {
              attack: 170,
              defense: 170,
              magicAttack: 240,
              magicDefense: 240,
            },
          ],
        },
      ],
    },
    {
      id: 1,
      firstName: 'Lavitz',
      lastName: 'Slambert',
      element: Element.WIND,
      species: Species.HUMAN,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 2,
      firstName: 'Shana',
      lastName: null,
      element: Element.LIGHT,
      species: Species.HUMAN,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 3,
      firstName: 'Rose',
      lastName: null,
      element: Element.DARK,
      species: Species.HUMAN,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 4,
      firstName: 'Haschel',
      lastName: null,
      element: Element.THUNDER,
      species: Species.HUMAN,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 5,
      firstName: 'Albert',
      lastName: null,
      element: Element.WIND,
      species: Species.HUMAN,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 6,
      firstName: 'Meru',
      lastName: null,
      element: Element.WATER,
      species: Species.WINGLY,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 7,
      firstName: 'Kongol',
      lastName: null,
      element: Element.EARTH,
      species: Species.GIGANTO,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
    {
      id: 8,
      firstName: 'Miranda',
      lastName: null,
      element: Element.LIGHT,
      species: Species.HUMAN,
      additions: null,
      bodyStats: null,
      dragoons: null,
    },
  ];

  constructor(@Optional() @SkipSelf() parentModule?: GameDataComponent) {
    if (parentModule) {
      throw new Error('GameDataService is already loaded. Import it in the GameDataComponent only');
    }
  }
}
